### ISSUE TITLE
NullPointer al arxivar fitxer firmat des de APIFIRMASIMPLE

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#140]
Pareix que la informació que retorna la realització de la firma no inclou el perfil de firma (BES o EPES) ja que és on falla dins el plugin d'arxiu (Linia 478 de ArxiuConversioHelper.java)

es.caib.plugins.arxiu.api.ArxiuException: S'ha produit un error cridant el mètode /services/createDocument
	at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.documentCrear(ArxiuPluginCaib.java:649)
	at es.caib.digitalib.logic.PluginArxiuLogicaEJB.custodiaAmbApiArxiu(PluginArxiuLogicaEJB.java:413)

Caused by: java.lang.NullPointerException
	at es.caib.plugins.arxiu.caib.ArxiuConversioHelper.toMetadataDocument(ArxiuConversioHelper.java:478)
	at es.caib.plugins.arxiu.caib.ArxiuConversioHelper.documentToDocumentNode(ArxiuConversioHelper.java:135)

**Comment by anadal-fundaciobit** [comment]
Pareix que és un error de l'API de Firma Simple de PortaFIB que retorna el Perfil a NULL. 
He creat un issue a dins de PortaFIB. ApiFirma Simple en Servidor Rest retorna Perfil de Firma null (https://github.com/GovernIB/portafib/issues/594) i dins DigitalIB he fet un petit parxe indicant que si Perfil val null llavors posi per defecte "BES"
