### ISSUE TITLE
Error de java.util.ConcurrentModificationException a es.caib.digitalib.logic.ScanWebModuleEjb

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#156]
Error de java.util.ConcurrentModificationException a es.caib.digitalib.logic.ScanWebModuleEjb. Segurament es fa una inserció o esborrat a la vegada que un llistat. Revisar el codi.

```
2021-10-01 10:53:50,386 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[localhost].[/digitalib].[digitalibback]] (http-10.215.5.56-28080-112) Servlet.service() para servlet digitalibback lanzó excepción
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$KeyIterator.next(HashMap.java:956)
	at es.caib.digitalib.logic.ScanWebModuleEjb.getScanWebConfig(ScanWebModuleEjb.java:264)
	at es.caib.digitalib.logic.ScanWebModuleEjb.getAllPluginsFiltered(ScanWebModuleEjb.java:55)
	at sun.reflect.GeneratedMethodAccessor635.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
[...]
	at java.lang.Thread.run(Thread.java:745)
2021-10-01 10:53:50,388 ERROR [org.apache.jsp.error_jsp] (http-10.215.5.56-28080-112)  =================  FINAL ERROR.JSP (87)
2021-10-01 10:54:07,460 WARN  [es.limit.pluginsib.scanweb.dynamicwebtwain.DynamicWebTwainScanWebPlugin] (http-10.215.5.56-28080-89) PAS 1: Error parsejant DWT version to double(14.3.1): multiple points
2021-10-01 10:54:34,728 WARN  [es.limit.pluginsib.scanweb.dynamicwebtwain.DynamicWebTwainScanWebPlugin] (http-10.215.5.56-28080-21) PAS 1: Error parsejant DWT version to double(14.3.1): multiple points
```

**Comment by anadal-fundaciobit** [comment]
Solucionat.
