### ISSUE TITLE
Error intentant inserir una descripció NULL a una TransaccioNMultiple

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#178]
Via web al intentar escanejar es produeix aquest error a la CAIB:

```
2021-11-25 08:52:04,276 INFO  [es.caib.digitalib.back.controller.user.ScanWebProcessControllerUser] (http-10.215.29.9-18080-5) XYZ ZZZ baseUrlFull = https://dev.caib.es/digitalib/user/llistatperfilsdisponibles
2021-11-25 08:52:04,276 INFO  [es.caib.digitalib.back.controller.user.ScanWebProcessControllerUser] (http-10.215.29.9-18080-5) XYZ ZZZ Tipus Perfil = 3
2021-11-25 08:52:04,276 INFO  [es.caib.digitalib.back.controller.user.ScanWebProcessControllerUser] (http-10.215.29.9-18080-5) XYZ ZZZ POS Perfil = 1
2021-11-25 08:52:04,276 INFO  [es.caib.digitalib.back.controller.user.ScanWebProcessControllerUser] (http-10.215.29.9-18080-5) XYZ ZZZ Username = u139636
2021-11-25 08:52:04,292 INFO  [es.caib.digitalib.back.controller.user.ScanWebProcessControllerUser] (http-10.215.29.9-18080-5) XYZ ZZZ usuariPersonaID = 5390
2021-11-25 08:52:04,342 INFO  [es.caib.digitalib.back.controller.user.ScanWebProcessControllerUser] (http-10.215.29.9-18080-5) PERFIL CODI = ARXIU
2021-11-25 08:52:04,378 INFO  [es.caib.digitalib.back.controller.user.ScanWebProcessControllerUser] (http-10.215.29.9-18080-5) XYZ ZZZ  baseUrl OK = https://dev.caib.es/digitalib
2021-11-25 08:52:04,600 WARN  [org.hibernate.util.JDBCExceptionReporter] (http-10.215.29.9-18080-5) SQL Error: 1400, SQLState: 23000
2021-11-25 08:52:04,600 ERROR [org.hibernate.util.JDBCExceptionReporter] (http-10.215.29.9-18080-5) ORA-01400: no se puede realizar una inserción NULL en ("DIGITALIB"."DIB_TRANSMULTIPLE"."DESCRIPCIO")

2021-11-25 08:52:04,601 WARN  [org.hibernate.util.JDBCExceptionReporter] (http-10.215.29.9-18080-5) SQL Error: 1400, SQLState: 23000
2021-11-25 08:52:04,601 ERROR [org.hibernate.util.JDBCExceptionReporter] (http-10.215.29.9-18080-5) ORA-01400: no se puede realizar una inserción NULL en ("DIGITALIB"."DIB_TRANSMULTIPLE"."DESCRIPCIO")

2021-11-25 08:52:04,602 ERROR [org.hibernate.event.def.AbstractFlushingEventListener] (http-10.215.29.9-18080-5) Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:94)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
```

**Comment by anadal-fundaciobit** [comment]
Resulta que Oracle té la fantàstica característica de convertir les cadenes buides a NULL "por la cara". D'aquí el no deixi incloure NULL en un camp not null. Quan provenim d'una petició REST aquest valor no val NULL, però des de Web aquest valor s'assigna temporalment a "" per ser modificat a posteriori.

**Comment by anadal-fundaciobit** [comment]
Solucionat, enlooc de posar temporalment una cadena buida, posam un espai.
