### ISSUE TITLE
Implementar reintents per  l'error de "Contingut no trobat"

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#187]
Revisar l'error de "Contingut no trobat" relacionat amb l'Arxiu, que ja vàrem parlar. Entre dia 10 i 11 de gener, s'han fet 86 transaccions a DigitalIB standalone i hi ha hagut 10 errors, tots ells per aquest error 

SOLUCIÓ: Quan ocorri l'excepció fer un bucle de 2 o 3 intents de guardar l'arxiu: allargaria en els casos de l'error el temps d'execució, però evitaria llançament d'errors. Esperar 1segon entre cridades.

```
es.caib.plugins.arxiu.api.ArxiuNotFoundException: Contingut no trobat
        at es.caib.plugins.arxiu.caib.ArxiuCaibClient.generarExcepcioJson(ArxiuCaibClient.java:248)
        at es.caib.plugins.arxiu.caib.ArxiuCaibClient.generarEnviarPeticio(ArxiuCaibClient.java:142)
        at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.documentVersionsComu(ArxiuPluginCaib.java:1368)
        at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.documentDarreraVersio(ArxiuPluginCaib.java:1403)
        at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.documentDetalls(ArxiuPluginCaib.java:779)
        at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.getCsv(ArxiuPluginCaib.java:1752)
        at es.caib.plugins.arxiu.api.AbstractArxiuPlugin.processExpressionLanguage(AbstractArxiuPlugin.java:131)
        at es.caib.plugins.arxiu.api.AbstractArxiuPlugin.getOriginalFileUrl(AbstractArxiuPlugin.java:59)
        at es.caib.digitalib.logic.PluginArxiuLogicaEJB.custodiaAmbApiArxiu(PluginArxiuLogicaEJB.java:488)
        at sun.reflect.GeneratedMethodAccessor867.invoke(Unknown Source)
```

**Comment by anadal-fundaciobit** [comment]
Solucionat. Pero una millor solució és la del issue  Actualitzar API de PLugin Arxiu per atacar nous mètodes de getURL*() #191  que evita cridades a Arxiu per cada URL* a consultar.
