### ISSUE TITLE
Error desconegut durant la neteja nocturna de transaccions

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/digitalib#245]
Error desconegut durant la neteja nocturna de transaccions. Revisar que pot ser:

```
Caused by: java.lang.NullPointerException
	at deployment.digitalib.ear.digitalib-ejb.jar//es.caib.digitalib.logic.TransaccioLogicaEJB.netejaDeFitxersNocturn(TransaccioLogicaEJB.java:930)
	at deployment.digitalib.ear.digitalib-ejb.jar//es.caib.digitalib.logic.TransaccioLogicaEJB.netejaDeFitxersNocturnAplicacio(TransaccioLogicaEJB.java:856)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by anadal-fundaciobit** [comment]
Solucionat.
